// ERROR:
fn foo() {
}

// ERROR:
fn foo2(a: u32) {
}

// ERROR:
fn foo2(a: u32) -> u32 {
}
