# ERROR: match
def foo(a, b):
    return 1
