def a():
  #ERROR: match
  try:
    bad
  except Exception:
    logger.error("Something bad happened")

