=== command
CI="true" GITHUB_ACTIONS="true" GITHUB_EVENT_NAME="unknown" GITHUB_REPOSITORY="project_name/project_name" GITHUB_RUN_ID="35" GITHUB_ACTOR="some_test_username" GITHUB_REF="some/branch-name" GITHUB_EVENT_PATH="/private<MASKED>" SEMGREP_APP_TOKEN="fake-key-from-tests" SEMGREP_MOCK_NETWORK="/private<MASKED>" SEMGREP_USER_AGENT_APPEND="pytest" SEMGREP_SETTINGS_FILE="<MASKED>" SEMGREP_VERSION_CACHE_PATH="<MASKED>" SEMGREP_ENABLE_VERSION_CHECK="0" SEMGREP_SEND_METRICS="off" semgrep ci --no-suppress-errors --allow-untrusted-validators
=== end of command

=== exit code
1
=== end of exit code

=== stdout - plain


┌────────────────┐
│ Debugging Info │
└────────────────┘

  SCAN ENVIRONMENT
  versions    - semgrep <MASKED> on python <MASKED>
  environment - running in environment github-actions, triggering event is unknown

  CONNECTION
  Initializing scan (deployment=org_name, scan_id=12345)
  Enabled products: Code, Supply Chain, Secrets

  ENGINE
  Semgrep Secrets requires Semgrep Pro Engine
  Using Semgrep Pro Version: 0.120.0-15-g8dfe2aac-dirty
  Installed at /Users/cooper/dev/pro/semgrep/cli/src/semgrep/bin/semgrep-core-proprietary


┌─────────────┐
│ Scan Status │
└─────────────┘
  Scanning 1 file tracked by git with 0 Code rules, 1 Secrets rule:


  CODE RULES
  Nothing to scan.

  SECRETS RULES
  Scanning 1 file.
Semgrep Pro Engine may be slower and show different results than Semgrep OSS.


┌─────────────────────────┐
│ Secrets Historical Scan │
└─────────────────────────┘


┌─────────────┐
│ Scan Status │
└─────────────┘
  Scanning 1 file tracked by git with 0 Code rules, 1 Secrets rule:


  CODE RULES
  Nothing to scan.

  SECRETS RULES
  Scanning 1 file.
Semgrep Pro Engine may be slower and show different results than Semgrep OSS.


┌─────────────────────────┐
│ 1 Valid Secrets Finding │
└─────────────────────────┘

    foo.py@2402382a02e2366105d3147ad52813a8c5d717bb
   ❯❯❱ secret
          found secret

            2┆ return "M*********


┌───────────────────────────┐
│ 1 Invalid Secrets Finding │
└───────────────────────────┘

    foo.py
   ❯❯❱ secret
          found secret

            2┆ return "D********
  1 rule ran in a within-a-file fashion because `interfile: true` was not specified.
  (Use --verbose to see which ones.)



┌──────────────┐
│ Scan Summary │
└──────────────┘
Some files were skipped or only partially analyzed.
  Scan was limited to files tracked by git.

CI scan completed successfully.
  Found 2 findings (2 blocking) from 2 rules.
  Uploading scan results
  Finalizing scan           View results in Semgrep Cloud Platform:
    https://semgrep.dev/orgs/org_name/findings?repo=project_name/project_name&ref=some/branch-name
  Has findings for blocking rules so exiting with code 1
  semgrep.dev is suggesting a non-zero exit code (Test Reason)

=== end of stdout - plain

=== stderr - plain

=== end of stderr - plain

=== stdout - color
<same as above: stdout - plain>
=== end of stdout - color

=== stderr - color
<same as above: stderr - plain>
=== end of stderr - color