def foo do
    # ERROR:
    foo(bar(42 + 1))
end
