
fn foo() {
    //ERROR:
    let x = 42;
}
