// We don't want findings! If we produce a finding, that means something is wrong with `inside`.
func foo() {

	x := 5 

	if cond { }

	return 0 
}
